#! /bin/bash

echo "Installing RStudio Server build dependencies"
apt-get update
apt-get install -qqy --no-install-recommends \
  ant \
  build-essential \
  cmake \
  curl \
  libpam0g-dev \
  libssl-dev \
  openjdk-8-jre-headless \
  openjdk-8-jdk-headless \
  pandoc \
  pandoc-citeproc \
  r-base-dev \
  tar \
  time \
  uuid-dev

rm -fr rstudio*
curl -Ls https://github.com/rstudio/rstudio/tarball/$RSTUDIO_TAG \
  | tar xzf -
mv rstudio-rstudio-* rstudio
cd rstudio

# Non-L4t Dependencies
export PANDOC_VERSION=`pandoc --version|head -n 1|sed 's/^pandoc //'`
echo "PANDOC_VERSION=$PANDOC_VERSION"
pushd dependencies/common && \
  echo "Installing RStudio boost from source - may take a while"
  /usr/bin/time ./install-boost > $SOURCE_DIR/install-boost.log 2>&1 && \
  gzip -9 $SOURCE_DIR/install-boost.log && \
  ./install-dictionaries > /dev/null 2>&1 && \
  ./install-mathjax > /dev/null 2>&1 && \
  mkdir -p pandoc/$PANDOC_VERSION/ && \
  cp /usr/bin/pandoc* pandoc/$PANDOC_VERSION/
popd

echo "CMake"
mkdir --parents $SOURCE_DIR/rstudio/build/ && cd $SOURCE_DIR/rstudio/build/
cmake .. \
  -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=TGZ -DCPACK_SOURCE_GENERATOR=TGZ

echo "Packaging"

# The Nano only has 4 GB of RAM. As a result, the Java builds swamp the available
# RAM and multi-job makes are problematic - they swap and the system appears
# unresponsive.
#
# So we only run multi-job makes if we have more than 5 GB of RAM.
export RAM_KILOBYTES=`grep MemTotal /proc/meminfo | sed 's/^MemTotal:  *//' | sed 's/ .*$//'`
if [ $RAM_KILOBYTES -gt "5000000" ]
then
  export JOBS=`nproc`
else
  export JOBS=1
fi
echo "RAM_KILOBYTES = $RAM_KILOBYTES; 'make' will use $JOBS jobs."
/usr/bin/time make --jobs=$JOBS package

echo "RStudio Server package tarball is in $SOURCE_DIR/rstudio/build/$PACKAGE_FILE"
echo "Install with 'tar --directory=/ --strip-components=1 -xvf $PACKAGE_FILE'"

echo "Checking tarball"
/usr/bin/time make --jobs=$JOBS install
tar xf $SOURCE_DIR/rstudio/build/$PACKAGE_FILE
diff --recursive \
  ./rstudio-server-$RSTUDIO_VERSION-arm64/usr/local/lib/rstudio-server/ \
  /usr/local/lib/rstudio-server/ \
  > $SOURCE_DIR/install-tarball-diff.log 
