#! /bin/bash

source $WORKON_HOME/r-reticulate/bin/activate
alias make="make --jobs=`nproc`"

echo "Installing 'numpy' and 'SymPy'"
/usr/bin/time pip install --upgrade numpy SymPy

echo "Installing PyTorch"
# https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-5-0-now-available/72048
wget -q https://nvidia.box.com/shared/static/3ibazbiwtkl181n95n9em3wtrca7tdzp.whl \
  -O /tmp/torch-1.5.0-cp36-cp36m-linux_aarch64.whl
pip install --upgrade Cython
pip install --upgrade /tmp/torch-1.5.0-cp36-cp36m-linux_aarch64.whl

pip list
