#! /bin/bash

source $WORKON_HOME/r-reticulate/bin/activate
alias make="make --jobs=`nproc`"

echo "Installing PyTorch audio v0.5.0 from source"
curl -Ls https://github.com/pytorch/audio/archive/v0.5.0.tar.gz \
  | tar xzf -
cd audio-0.5.0
python setup.py install
cd ..
rm -fr audio-0.5.0

pip list
