#! /bin/bash

echo "Upgrading NVIDIA base"
apt-get update
apt-get install -qqy --no-install-recommends time tzdata bash-completion
/usr/bin/time apt-get upgrade -y
apt-get autoremove --purge -y

if [ $BUILDING_DOCKER_IMAGE = "yes" ]
then
  echo "Cleanup"
  apt-get clean
fi
