#! /bin/bash

# build Bionic image
/usr/bin/time sudo docker build \
  --build-arg BASE_IMAGE="ubuntu:bionic" \
  --build-arg R_SOURCE_TARBALL="https://cloud.r-project.org/src/base/R-4/R-4.0.1.tar.gz" \
  --build-arg RSTUDIO_VERSION_MAJOR=1 \
  --build-arg RSTUDIO_VERSION_MINOR=3 \
  --build-arg RSTUDIO_VERSION_PATCH=959 \
  --tag="znmeb/algocompsynth-`uname -m`-bionic:latest" --file=Dockerfile .

# Build L4T image on Tegra host only
if [ `uname -r | grep tegra | wc -l` -gt "0" ]
then
  /usr/bin/time sudo docker build \
    --build-arg BASE_IMAGE="nvcr.io/nvidia/l4t-base:r32.4.2" \
    --build-arg R_SOURCE_TARBALL="https://cloud.r-project.org/src/base/R-4/R-4.0.1.tar.gz" \
    --build-arg RSTUDIO_VERSION_MAJOR=1 \
    --build-arg RSTUDIO_VERSION_MINOR=3 \
    --build-arg RSTUDIO_VERSION_PATCH=959 \
    --tag="znmeb/algocompsynth-jetson-l4t:latest" --file=Dockerfile .
fi

docker system prune
sudo docker images
