#! /bin/bash

set -e

sudo docker login
sudo docker images

# push Bionic image
/usr/bin/time sudo docker push "znmeb/algocompsynth-`uname -m`-bionic:latest"

# push L4T image on Tegra host only
if [ `uname -r | grep tegra | wc -l` -gt "0" ]
then
  /usr/bin/time sudo docker push "znmeb/algocompsynth-jetson-l4t:latest"
fi
