#! /bin/bash

echo "Installing Linux dependencies"
apt-get install -qqy --no-install-recommends \
  hdf5-tools \
  libffi-dev \
  libfftw3-dev \
  libhdf5-dev \
  libhdf5-serial-dev \
  libjpeg8-dev \
  libopenblas-base \
  libopenmpi-dev \
  libsndfile1-dev \
  libsodium-dev \
  libsox-dev \
  libsox-fmt-all \
  libsoxr-dev \
  libssh2-1-dev \
  libssl-dev \
  libxml2-dev \
  python-dev \
  python3-dev \
  python-pip \
  python3-pip \
  python-virtualenv \
  python3-virtualenv \
  sndfile-tools \
  sox \
  virtualenv \
  virtualenvwrapper \
  zlib1g-dev
apt-get autoremove --purge -y

if [ $BUILDING_DOCKER_IMAGE == "yes" ]
then
  apt-get clean
fi
