#! /bin/bash

set -e

source $WORKON_HOME/r-reticulate/bin/activate
alias make="make --jobs=`nproc`"

echo "Installing 'Cython', 'numpy' and 'SymPy'"
/usr/bin/time pip install --upgrade Cython numpy SymPy

pip list
